language: python

matrix:
  include:
    - os: linux
      env:
        - LUA="lua=5.3"
    - os: linux
      env:
        - LUA="lua=5.4"

before_install:
  - pip2 install codecov
  - pip2 install hererocks
  - hererocks lua_install --$LUA -r latest
  - source lua_install/bin/activate
  - luarocks install install --deps-only lr-stack-manager-dev-1.rockspec
  - luarocks install cluacov
  - luarocks install luacheck

install:
  - luarocks make

script:
  - busted -c

after_script:
  - luacov
  - codecov -X gcov