name: test

on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        luaVersion: ["lua:5.1", "lua:5.4"]
        machineTag: ["ubuntu-latest"]

    runs-on: ${{ matrix.machineTag }}

    container:
      image: nickblah/${{ matrix.luaVersion }}-luarocks-alpine

    steps:
    - uses: actions/checkout@main

    - name: add binary packages
      run: apk add --no-cache build-base gcc

    - name: install packages
      run: luarocks install --deps-only lr-stack-manager-dev-1.rockspec

    - name: test
      run: busted -c
